apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-disk
#  namespace: app1
spec: 
  accessModes: 
  - ReadWriteOnce
  resources:
    requests: 
      storage: 20Gi
  storageClassName: csi-disk
