admin:
  existingSecret: grafana-admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
#      isDefault: true
      name: Loki
      type: loki
      url: http://loki-gateway
ingress:
  enabled: true
  hosts:
  - loki-grafana.local.domain
  ingressClassName: nginx
initChownData:
  enabled: false
persistence:
  enabled: true
  storageClassName: nfs-client

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    # Allow discovery in all namespaces for dashboards
    searchNamespace: ALL

  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
