serviceMonitor:
  selfMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  enabled: true
  # Default values that will be used for all ServiceMonitors created by `targets`
  defaults:
    labels:
      release: kube-prometheus-stack
  targets:
#    - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
#      url: http://example.com/healthz  # The URL that blackbox will scrape
#      hostname: example.com            # HTTP probes can accept an additional `hostname` parameter that will set `Host` header and TLS SNI
#      labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
#      interval: 60s                    # Scraping interval. Overrides value set in `defaults`
#      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
#      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
#      additionalMetricsRelabels: {}    # Map of metric labels and values to add
#      additionalRelabeling: []         # List of metric relabeling actions to run
    - name: blackbox-demo                    # Human readable URL that will appear in Prometheus / AlertManager
      url: https://status.python.org/  # The URL that blackbox will scrape
#      hostname: example.com            # HTTP probes can accept an additional `hostname` parameter that will set `Host` header and TLS SNI
      labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
      interval: 60s                    # Scraping interval. Overrides value set in `defaults`
      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
      additionalMetricsRelabels: {}    # Map of metric labels and values to add
      additionalRelabeling: []         # List of metric relabeling actions to run

configReloader:
  enabled: true
