apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: local-pvc
spec: 
  storageClassName: local-storageclass
  accessModes:
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 20Gi
