apiVersion: v1
kind: PersistentVolume
metadata: 
  name: local-pv
spec: 
  capacity: 
    storage: 20Gi
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storageclass
  local: 
    path: /mnt/disk/ssd1
  nodeAffinity:  #限制该PV只能在node001k8s上被使用
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname  #拓扑域限制：单node可访问
          operator: In
          values:
          - node001k8s
