apiVersion: v1
kind: Pod
metadata:
  labels:
    component: registry
    tier: control-plane
  name: registry
  namespace: kube-system
spec:
  containers:
  - image: registry:2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 15
    name: registry
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 15
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
    volumeMounts:
    - mountPath: /var/lib/registry
      name: data
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /var/lib/registry
      type: DirectoryOrCreate
    name: data
