apiVersion: batch/v1
kind: Job
metadata: 
  name: pi
spec: 
  activeDeadlineSeconds: 60  # job运行的超时时间，job运行超过该时间，停止启动新的pod
  completions: 10  # 需要运行的pod数量
  parallelism: 2  # 允许并行的pod数量
  backoffLimit: 3  # pod运行失败后的重启次数
  template: 
    spec: 
      containers: 
      - name: pi
        image: registry-vpc.cn-shanghai.aliyuncs.com/pro1/perl:v1
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      imagePullSecrets: 
      - name: image-sec
      restartPolicy: Never  # 重启策略
