apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: rancher
  namespace: rancher
  labels: 
    app: rancher
spec: 
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: rancher
  serviceName: "rancher"
  replicas: 1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: rancher
    spec:
      containers: 
      - name: rancher
        image: rancher/rancher:latest
        ports: 
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: data
          mountPath: /var/lib/rancher
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: rancher
      terminationGracePeriodSeconds: 30
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
      storageClassName: nfs-client

---

apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: rancher
  labels:
    app: rancher
spec:
  selector:
    app: rancher
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  sessionAffinity: ClientIP
  type: NodePort
