apiVersion: v1
kind: Service
metadata:
  name: example-proxy
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Endpoints
metadata:
  name: example-proxy
  namespace: default
subsets:
  - addresses:
    - ip: 202.119.86.22
    - ip: 202.119.86.103
    - ip: 202.119.86.104
    ports:
    - port: 8080
