apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: default
spec:
  externalName: www.example.com
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ExternalName

