apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: etcd
  name: kube-prometheus-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
    targetPort: 2381
  selector:
    component: etcd
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: etcd
  name: kube-prometheus-etcd
  namespace: prometheus
spec:
  endpoints:
  - port: http-metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/component: etcd
