---
# Source: ingress-nginx/templates/controller-service-metrics.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.2.3
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller-metrics
  namespace: ingress-nginx
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 10254
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller



---
# Source: ingress-nginx/templates/controller-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-controller
  labels:
    helm.sh/chart: ingress-nginx-4.2.3
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
spec:
  endpoints:
    - port: http-metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller


##################### or #######################

#
#---
## Source: nginx-ingress-controller/templates/controller-metrics-service.yaml
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-ingress-controller-metrics
#  namespace: "ingress-nginx"
#  labels:
#    app.kubernetes.io/name: nginx-ingress-controller
#    helm.sh/chart: nginx-ingress-controller-9.2.2
#    app.kubernetes.io/instance: nginx-ingress-controller
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/component: metrics
#  annotations:
#    prometheus.io/port: '9913'
#    prometheus.io/scrape: "true"
#spec:
#  type: ClusterIP
#  ports:
#    - name: metrics
#      port: 9913
#      targetPort: metrics
#  selector:
#    app.kubernetes.io/name: nginx-ingress-controller
#    app.kubernetes.io/instance: nginx-ingress-controller
#    app.kubernetes.io/component: controller
#
#
#
#---
## Source: nginx-ingress-controller/templates/controller-servicemonitor.yaml
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: nginx-ingress-controller
#  namespace: "ingress-nginx"
#  labels:
#    app.kubernetes.io/name: nginx-ingress-controller
#    helm.sh/chart: nginx-ingress-controller-9.2.2
#    app.kubernetes.io/instance: nginx-ingress-controller
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/component: metrics
#spec:
#  jobLabel: ""
#  endpoints:
#    - port: metrics
#      interval: 30s
#  namespaceSelector:
#    matchNames:
#      - ingress-nginx
#  selector:
#    matchLabels:
#      app.kubernetes.io/name: nginx-ingress-controller
#      app.kubernetes.io/instance: nginx-ingress-controller
#      app.kubernetes.io/component: metrics
